
package ar.edu.ubp.das.src.comercio.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.4
 * Sat Jan 19 22:33:09 ART 2019
 * Generated source version: 3.2.4
 */

@XmlRootElement(name = "getOfertas", namespace = "http://ws.comercio.src.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOfertas", namespace = "http://ws.comercio.src.das.ubp.edu.ar/")

public class GetOfertas {


}

