
package ar.edu.ubp.das.src.comercio.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.4
 * Mon Feb 04 01:32:54 ART 2019
 * Generated source version: 3.2.4
 */

@XmlRootElement(name = "notifyTransaccionResponse", namespace = "http://ws.comercio.src.das.ubp.edu.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "notifyTransaccionResponse", namespace = "http://ws.comercio.src.das.ubp.edu.ar/")

public class NotifyTransaccionResponse {

    @XmlElement(name = "return")
    private ar.edu.ubp.das.src.beans.ResponseBean _return;

    public ar.edu.ubp.das.src.beans.ResponseBean getReturn() {
        return this._return;
    }

    public void setReturn(ar.edu.ubp.das.src.beans.ResponseBean new_return)  {
        this._return = new_return;
    }

}

