
package ar.edu.ubp.das.src.comercio.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-01-19T22:33:10.042-03:00
 * Generated source version: 3.2.4
 *
 */

public class OfertasWS_PortTypeServer{

    protected OfertasWS_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.src.comercio.ws.OfertasWS();
        String address = "http://localhost:9090/OfertasWSPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new OfertasWS_PortTypeServer();
        System.out.println("Server for Ofertas ready...");

//        Thread.sleep(5 * 60 * 1000);
//        System.out.println("Server exiting");
//        System.exit(0);
    }
}

