
package ar.edu.ubp.das.src.comercio.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-01-19T23:55:57.594-03:00
 * Generated source version: 3.2.4
 *
 */

public class TransaccionWS_PortTypeServer{

    protected TransaccionWS_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.src.comercio.ws.TransaccionWS();
        String address = "http://localhost:9091/TransaccionWSPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new TransaccionWS_PortTypeServer();
        System.out.println("Server for Transaccion ready...");

//        Thread.sleep(5 * 60 * 1000);
//        System.out.println("Server exiting");
//        System.exit(0);
    }
}

